spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/test
  main:
    allow-bean-definition-overriding: 'true'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      springframework:
        nodeValue: debug
        web: debug


#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    password:
#    driver-class-name: org.h2.Driver
#
#    jpa:
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
#          # show_sql: true
#          format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug
